#Testing about CI


trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'




    
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/CodeScanning.Server.csproj'
    arguments: '--configuration release --output $(Build.ArtifactStagingDirectory) '
    

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dll_file'
    publishLocation: 'Container'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/*.zip'  # Specify the path to the zip file
    destinationFolder: '$(Build.ArtifactStagingDirectory)/extracted'  # Specify the folder where you want to extract the files
